### ISSUE TITLE
How can I add parameters as well when publishing to a topic, like "-r 100"

### ISSUE THREAD

**Issue by Ouissalb** [h2r/java_rosbridge#8]
I want to be able to send the following : 

rostopic pub /robot/limb/right/joint_command baxter_core_msgs/JointCommand "{mode: 1, command: [0.0, 1.91, -0.047, -1.38, -0.24, 1.084, -0.069], names: ['right_e0', 'right_e1','right_s0',  'right_s1', 'right_w0', 'right_w1', 'right_w2']}" -r 100

I have this publisher : 

Publisher pubSonar = new Publisher(rosTopic,topicType, bridge);
But apparently the publisher can only have  3 arguments, which are the topic, the type and the rosbridge, but how can I give it also that "-r 100" parameter? 

Thank you.

**Comment by jmacglashan** [comment]
It looks like you resolved it, but the Publisher is not meant to mimic the command line tool rostopic pub; it's meant to mimic something like `Publisher` in rospy. The rospy implementation doesn't have a `-r` argument either, because in that setting you have full programmatic control, so if you want to publish the same data on a fixed hrz, you can just add a loop to wait the requisite time between calls and publish each time.

That said, there is a tool you can use for this kind of scenario: [PeriodicPublisher](https://github.com/h2r/java_rosbridge/blob/master/src/ros/tools/PeriodicPublisher.java). This tool is more powerful than the rostopic -r because not only does it publish data on a fixed interval, but you can mutate it from a separate thread.
